name: Print Env Variable and Base64 Encode Secret

on:
  pull_request:
    types: [opened, reopened]

jobs:
  print_and_base64_encode:
    runs-on: ubuntu-latest

    steps:
      - name: Print Environment Variable
        run: env

      - name: Base64 Encode Organization Secret
        run: |
          TEST_SECRET=${{ secrets.FLAG }} python -c "import os;print(os.environ['FLAG'])"